# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/Desktop/HTTP_WEB_C

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/Desktop/HTTP_WEB_C

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Desktop/HTTP_WEB_C/CMakeFiles /home/pi/Desktop/HTTP_WEB_C//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Desktop/HTTP_WEB_C/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named HTTP_WEB_C

# Build rule for target.
HTTP_WEB_C: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 HTTP_WEB_C
.PHONY : HTTP_WEB_C

# fast build rule for target.
HTTP_WEB_C/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_WEB_C.dir/build.make CMakeFiles/HTTP_WEB_C.dir/build
.PHONY : HTTP_WEB_C/fast

#=============================================================================
# Target rules for targets named unit_tests

# Build rule for target.
unit_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit_tests
.PHONY : unit_tests

# fast build rule for target.
unit_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/build
.PHONY : unit_tests/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

BME280.o: BME280.cpp.o
.PHONY : BME280.o

# target to build an object file
BME280.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_WEB_C.dir/build.make CMakeFiles/HTTP_WEB_C.dir/BME280.cpp.o
.PHONY : BME280.cpp.o

BME280.i: BME280.cpp.i
.PHONY : BME280.i

# target to preprocess a source file
BME280.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_WEB_C.dir/build.make CMakeFiles/HTTP_WEB_C.dir/BME280.cpp.i
.PHONY : BME280.cpp.i

BME280.s: BME280.cpp.s
.PHONY : BME280.s

# target to generate assembly for a file
BME280.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_WEB_C.dir/build.make CMakeFiles/HTTP_WEB_C.dir/BME280.cpp.s
.PHONY : BME280.cpp.s

FileTypeDetector.o: FileTypeDetector.cpp.o
.PHONY : FileTypeDetector.o

# target to build an object file
FileTypeDetector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_WEB_C.dir/build.make CMakeFiles/HTTP_WEB_C.dir/FileTypeDetector.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/FileTypeDetector.cpp.o
.PHONY : FileTypeDetector.cpp.o

FileTypeDetector.i: FileTypeDetector.cpp.i
.PHONY : FileTypeDetector.i

# target to preprocess a source file
FileTypeDetector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_WEB_C.dir/build.make CMakeFiles/HTTP_WEB_C.dir/FileTypeDetector.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/FileTypeDetector.cpp.i
.PHONY : FileTypeDetector.cpp.i

FileTypeDetector.s: FileTypeDetector.cpp.s
.PHONY : FileTypeDetector.s

# target to generate assembly for a file
FileTypeDetector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_WEB_C.dir/build.make CMakeFiles/HTTP_WEB_C.dir/FileTypeDetector.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/FileTypeDetector.cpp.s
.PHONY : FileTypeDetector.cpp.s

generateHeaders.o: generateHeaders.cpp.o
.PHONY : generateHeaders.o

# target to build an object file
generateHeaders.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_WEB_C.dir/build.make CMakeFiles/HTTP_WEB_C.dir/generateHeaders.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/generateHeaders.cpp.o
.PHONY : generateHeaders.cpp.o

generateHeaders.i: generateHeaders.cpp.i
.PHONY : generateHeaders.i

# target to preprocess a source file
generateHeaders.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_WEB_C.dir/build.make CMakeFiles/HTTP_WEB_C.dir/generateHeaders.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/generateHeaders.cpp.i
.PHONY : generateHeaders.cpp.i

generateHeaders.s: generateHeaders.cpp.s
.PHONY : generateHeaders.s

# target to generate assembly for a file
generateHeaders.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_WEB_C.dir/build.make CMakeFiles/HTTP_WEB_C.dir/generateHeaders.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/generateHeaders.cpp.s
.PHONY : generateHeaders.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_WEB_C.dir/build.make CMakeFiles/HTTP_WEB_C.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_WEB_C.dir/build.make CMakeFiles/HTTP_WEB_C.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_WEB_C.dir/build.make CMakeFiles/HTTP_WEB_C.dir/main.cpp.s
.PHONY : main.cpp.s

parseString.o: parseString.cpp.o
.PHONY : parseString.o

# target to build an object file
parseString.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_WEB_C.dir/build.make CMakeFiles/HTTP_WEB_C.dir/parseString.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/parseString.cpp.o
.PHONY : parseString.cpp.o

parseString.i: parseString.cpp.i
.PHONY : parseString.i

# target to preprocess a source file
parseString.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_WEB_C.dir/build.make CMakeFiles/HTTP_WEB_C.dir/parseString.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/parseString.cpp.i
.PHONY : parseString.cpp.i

parseString.s: parseString.cpp.s
.PHONY : parseString.s

# target to generate assembly for a file
parseString.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_WEB_C.dir/build.make CMakeFiles/HTTP_WEB_C.dir/parseString.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/parseString.cpp.s
.PHONY : parseString.cpp.s

socket.o: socket.cpp.o
.PHONY : socket.o

# target to build an object file
socket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_WEB_C.dir/build.make CMakeFiles/HTTP_WEB_C.dir/socket.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/socket.cpp.o
.PHONY : socket.cpp.o

socket.i: socket.cpp.i
.PHONY : socket.i

# target to preprocess a source file
socket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_WEB_C.dir/build.make CMakeFiles/HTTP_WEB_C.dir/socket.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/socket.cpp.i
.PHONY : socket.cpp.i

socket.s: socket.cpp.s
.PHONY : socket.s

# target to generate assembly for a file
socket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_WEB_C.dir/build.make CMakeFiles/HTTP_WEB_C.dir/socket.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/socket.cpp.s
.PHONY : socket.cpp.s

socketSecure.o: socketSecure.cpp.o
.PHONY : socketSecure.o

# target to build an object file
socketSecure.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_WEB_C.dir/build.make CMakeFiles/HTTP_WEB_C.dir/socketSecure.cpp.o
.PHONY : socketSecure.cpp.o

socketSecure.i: socketSecure.cpp.i
.PHONY : socketSecure.i

# target to preprocess a source file
socketSecure.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_WEB_C.dir/build.make CMakeFiles/HTTP_WEB_C.dir/socketSecure.cpp.i
.PHONY : socketSecure.cpp.i

socketSecure.s: socketSecure.cpp.s
.PHONY : socketSecure.s

# target to generate assembly for a file
socketSecure.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_WEB_C.dir/build.make CMakeFiles/HTTP_WEB_C.dir/socketSecure.cpp.s
.PHONY : socketSecure.cpp.s

tests/FileTypeDetectorTest.o: tests/FileTypeDetectorTest.cc.o
.PHONY : tests/FileTypeDetectorTest.o

# target to build an object file
tests/FileTypeDetectorTest.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/FileTypeDetectorTest.cc.o
.PHONY : tests/FileTypeDetectorTest.cc.o

tests/FileTypeDetectorTest.i: tests/FileTypeDetectorTest.cc.i
.PHONY : tests/FileTypeDetectorTest.i

# target to preprocess a source file
tests/FileTypeDetectorTest.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/FileTypeDetectorTest.cc.i
.PHONY : tests/FileTypeDetectorTest.cc.i

tests/FileTypeDetectorTest.s: tests/FileTypeDetectorTest.cc.s
.PHONY : tests/FileTypeDetectorTest.s

# target to generate assembly for a file
tests/FileTypeDetectorTest.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/FileTypeDetectorTest.cc.s
.PHONY : tests/FileTypeDetectorTest.cc.s

tests/parseUnitTest.o: tests/parseUnitTest.cc.o
.PHONY : tests/parseUnitTest.o

# target to build an object file
tests/parseUnitTest.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/parseUnitTest.cc.o
.PHONY : tests/parseUnitTest.cc.o

tests/parseUnitTest.i: tests/parseUnitTest.cc.i
.PHONY : tests/parseUnitTest.i

# target to preprocess a source file
tests/parseUnitTest.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/parseUnitTest.cc.i
.PHONY : tests/parseUnitTest.cc.i

tests/parseUnitTest.s: tests/parseUnitTest.cc.s
.PHONY : tests/parseUnitTest.s

# target to generate assembly for a file
tests/parseUnitTest.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/parseUnitTest.cc.s
.PHONY : tests/parseUnitTest.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... HTTP_WEB_C"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... unit_tests"
	@echo "... BME280.o"
	@echo "... BME280.i"
	@echo "... BME280.s"
	@echo "... FileTypeDetector.o"
	@echo "... FileTypeDetector.i"
	@echo "... FileTypeDetector.s"
	@echo "... generateHeaders.o"
	@echo "... generateHeaders.i"
	@echo "... generateHeaders.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... parseString.o"
	@echo "... parseString.i"
	@echo "... parseString.s"
	@echo "... socket.o"
	@echo "... socket.i"
	@echo "... socket.s"
	@echo "... socketSecure.o"
	@echo "... socketSecure.i"
	@echo "... socketSecure.s"
	@echo "... tests/FileTypeDetectorTest.o"
	@echo "... tests/FileTypeDetectorTest.i"
	@echo "... tests/FileTypeDetectorTest.s"
	@echo "... tests/parseUnitTest.o"
	@echo "... tests/parseUnitTest.i"
	@echo "... tests/parseUnitTest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

