if(EXISTS "/home/pi/Desktop/HTTP_WEB_C/unit_tests[1]_tests.cmake")
  include("/home/pi/Desktop/HTTP_WEB_C/unit_tests[1]_tests.cmake")
else()
  add_test(unit_tests_NOT_BUILT unit_tests_NOT_BUILT)
endif()
