name: CMake on a single platform - armv6

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    
    - name: Run on ARMv6
      uses: uraimo/run-on-arch-action@v2
      with:
        arch: armv6
        distro: bookworm
        run: |
            sudo apt-get -y update 
            sudo apt-get -y install libboost-all-dev libgpiod-dev libgpiod2 libfreetype6-dev libfreetype6 pkg-config libssl-dev git cmake build-essential

            # Clone and build hiredis
            git clone https://github.com/redis/hiredis
            cd hiredis
            mkdir build && cd build
            cmake ..
            make
            sudo make install
            sudo ldconfig

            # Go back to the root directory of the project
            cd $GITHUB_WORKSPACE

            # Configure and build the project
            cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
            cmake --build build --config ${{env.BUILD_TYPE}}
    
    - name: Upload built executables
      uses: actions/upload-artifact@v3
      with:
        name: my-built-executables
        path: build/* # Adjust the path to the actual location of your built executables

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/* # Adjust the path to the actual location of your built executables
      env:
        GITHUB_TOKEN: ${{ secrets.A_TOKEN }}
