name: Sync Files from Repo A to Repo B

on:
  schedule:
    - cron: '0 0 * * *' # This sets the action to run daily at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  sync_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo B
      uses: actions/checkout@v3
      with:
        repository: monsieur7/HTTP_WEB_C
        token: ${{ secrets.B_TOKEN }}

    - name: Remove old files
      run: |
        rm -rf ./*

    - name: Checkout Repo A
      uses: actions/checkout@v3
      with:
        repository: monsieur7/INTELLIJ
        path: repo_A
        token: ${{ secrets.A_TOKEN }}

    - name: Copy files from A to B
      run: |
        cp -r ${{ github.workspace}}/INTELLIJ/html/* ${{ github.workspace }}/repo_A/www/

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m 'Sync files from Repo A'
        git push origin HEAD
      env:
        GITHUB_TOKEN: ${{ secrets.B_TOKEN }}
